<a href="https://colab.research.google.com/github/dpnaire/math/blob/main/practicas/practica_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Práctica 3. Álgebra
* Para aprender sobre Python vea la playlist [Python para Matemáticas](https://www.youtube.com/playlist?list=PL8gpDXwO-9l4HkDJ9QhB4H-cOiT0BYGau)
* Para obtener ideas y vídeos para la resolución de la práctica vea los archivos siguientes: [Ideas](https://github.com/financieras/math/tree/main/ideas)

## Práctica 3.4
**Matriz inversa en Python**  

Desarrolla un código en Python que al ejecutarse consiga los siguientes apartados.  
1. Crea una matriz cuadrada de dimensiones 3×3 usando números aleatorios enteros entre -9 y +9, excepto cero
2. Buscar un caso donde el determinante sea igual a 1
3. Si el determinante es 1 imprime la matriz y su determinante
4. Calcula e imprime su transpuesta
5. Calcula e imprime su matriz inversa
6. Multiplica la matriz creada por su inversa y comprueba que el producto es la matriz identidad.
7. Calcula cuantos segundos ha tardado en realizarse el proceso.

## Práctica 3.5
**Resolución de sistemas lineales en Python**  

1. Cree un sistema de 4 ecuaciones con 4 incógnitas con **solución única**.
2. La solución del sistema es: $\; \begin{pmatrix}x_1, x_2, x_3, x_4\end{pmatrix} = \begin{pmatrix} 3, 4, 5, 2\end{pmatrix}$  
3. Una de las ecuaciones del sistema es: $\enspace x_1+3x_2-x_3-2x_4=6$  
4. El vector $b$ de términos independientes es: $\enspace b=\begin{pmatrix}6, 3, 5, 7\end{pmatrix}$  
5. Usando números aleatorios elija los coeficientes que faltan de la matriz $A$ del sistema de ecuaciones.
  - Los coeficientes deben ser números enteros entre -5 y +5, excluido el cero.
  - Imprima la matriz $A$.  
6. Calcule e imprima el determinante de $A$.
7. Calcule e imprima la matriz inversa $A^{-1}$  
8. Resuelva el sistema lineal de ecuaciones con este método: $$Ax=b \quad \Longrightarrow \quad x=A^{-1}b$$
9. Compruebe que el resultado obtenido es la solución del sistema de ecuaciones.  
10. Resuelva nuevamente el sistema de ecuaciones usando ```np.linalg.solve```.

## Práctica 3.6
**Resolución de sistemas lineales con Octave**  

1. Tome el mismo sistema 4x4 con solución única del ejercicio anterior.

2. Muestra el sistema usando $\LaTeX$
3. Resuélvelo con Octave por dos métodos
4. ¿Ambos métodos dan el mismo resultado?

## Solución 3.6

$$\left.
\begin{align*}
2x - 4y +5z -t &= 5 \\
3x - 4y +4z -2t &= 1 \\
-x + 5y -5z +t &= -2 \\
4x - 3y -3z +2t &= -3
\end{align*}
\right\}$$

In [ ]:
!apt install octave

In [ ]:
!apt update

**MÉTODO 1**

In [ ]:
%%writefile primero.m
A = [2 -4 5 -1; 3 -4 4 -2; -1 5 -5 1; 4 -3 -3 2]
b = [5; -1; -2; -3]
x= inv(A)*b
% solución 1, rats expresa los número como fracciones o enteros
s1 =rats(x)

In [ ]:
!octave primero.m

**MÉTODO 2**  

In [ ]:
%%writefile segundo.m
A = [2 -4 5 -1; 3 -4 4 -2; -1 5 -5 1; 4 -3 -3 2]
b = [5; -1; -2; -3]
x = A\b
% solución 3 
s3 = rats(x)

In [ ]:
!octave segundo.m

***AMBOS MÉTODOS DAN EL MISMO RESULTADO***

## Práctica 3.7
**Diagonalización en Python**

* Sea la matriz cuadrada $A$ de orden 4x4

$$A=\left(
\begin{array}{rrrr}
 -1 &-2 &  3 &-1 \\
  0 & 2 &  0 & 0 \\
  0 & 0 &  2 & 0 \\
  0 & 0 &  0 & 1
\end{array}
\right)$$
1. Calcula los **autovalores** y **autovectores**
2. Calcula y muestra:
 - la matriz diagonal $D$
 - la matriz de paso $P$
 - su inversa $P^{-1}$  
3. Comprueba que se cumple que $A^3=PD^3P^{-1}$

## Solución 3.7

**1./2.** Calcula los **autovalores**, **autovectores**, la matriz diagonal $D$, la matriz de paso $P$ y su inversa $P^{-1}$

In [62]:
import numpy as np
A = np.array([[-1,-2,3,-1], [0,2,0,0], [0,0,2,0], [0,0,0,1]])
d,P = np.linalg.eig(A)
print("d: ", d)
D = np.diag(d)
print("\nD:\n", D)
print("\nP:\n", P)

d:  [-1.  2.  2.  1.]

D:
 [[-1.  0.  0.  0.]
 [ 0.  2.  0.  0.]
 [ 0.  0.  2.  0.]
 [ 0.  0.  0.  1.]]

P:
 [[ 1.         -0.5547002   0.70710678 -0.4472136 ]
 [ 0.          0.83205029  0.          0.        ]
 [ 0.          0.          0.70710678  0.        ]
 [ 0.          0.          0.          0.89442719]]


$A^3=PD^3P^{-1}$

In [63]:
import numpy as np
A = np.array([[-1,-2,3,-1], [0,2,0,0], [0,0,2,0], [0,0,0,1]])
print(A@A@A)

[[-1 -6  9 -1]
 [ 0  8  0  0]
 [ 0  0  8  0]
 [ 0  0  0  1]]


In [ ]:
import numpy as np
A = np.array([[-1,-2,3,-1], [0,2,0,0], [0,0,2,0], [0,0,0,1]])
d,P = np.linalg.eig(A)
print("d: ", d)
D = np.diag(d)
print("\nD:\n", D)
print("\nP:\n", P)
Dcubo = D @ D @ D
print("\nDcubo:\n", Dcubo)
print("\nSolución:\n", P @ Dcubo @ np.linalg.inv(P))

***SON COINCIDENTES***

## Práctica 3.8
**Diagonalización con Octave**

Resuelva el ejercicio anterior, pero en esta ocasión utilizando Octave.

## Solución 3.8

In [ ]:
!apt install octave

In [ ]:
!apt update

1./2. Calcula los autovalores, autovectores, la matriz diagonal  D , la matriz de paso  P  y su inversa  P−1

In [71]:
%%writefile diagonaliza.m
A = [-1,-2,3,-1; 0,2,0,0; 0,0,2,0; 0,0,0,1]
[P,D]=eig(A)
Pinv = P^-1

Overwriting diagonaliza.m


In [ ]:
!octave diagonaliza.m

$A^3=PD^3P^{-1}$

In [77]:
%%writefile diagonaliza.m
A = [-3,2,0,0; -3,4,0,0; 0,0,-5,-4; 0,0,-2,2]
[P,D]=eig(A)
Dcubo = D^3
Acubo = A^3
PxDcuboXPinv = P*Dcubo*P^-1

Overwriting diagonaliza.m


In [ ]:
!octave diagonaliza.m

***SON COINCIDENTES***

## Práctica 3.9
**Libertad para elegir el lugar de trabajo**  
Resolver con **Octave**.

Una empresa de 1.000 empleados permite que sus trabajadores cada día acudan a trabajar a la oficina o que realicen su trabajo desde su casa. Inicialmente el 90% de la plantilla trabajaba en la oficina y solo el 10% lo hacían en casa. Se ha observado que los que un día trabajan en casa tienen una probabilidad del 70% de realizarlo también desde casa al día siguiente, pero que en el restante 30% de los casos acuden a la oficina al día siguiente. Por el contrario, se ha observado que los que un día trabajaron en la oficina al día siguiente vuelven
a la oficina en el 60% de los casos y en el 40% restante van a su casa al día siguiente.
* Determinar qué número de empleados se quedan en casa transcurridos dos días.
* ¿Y a largo plazo cuantos se quedan en casa?

## Solución 3.9

In [ ]:
!apt install octave

In [ ]:
!apt update

* Determinar qué número de empleados se quedan en casa transcurridos dos días.

In [81]:
%%writefile proceso.m
empleados = 1000
% state vector
inicial = [.9; .1]
% transition probability matrix
A = [.6, .3; .4, .7]
[P,D]=eig(A)
Dcuadrado = D^2
Acuadrado = A^2
PxDcuadradoXPinv = P*Dcuadrado*P^-1
dia2 = Acuadrado * inicial
disp("Nº de empleados que se quedan en casa el segundo día: "), disp(dia2(2)*empleados)

Overwriting proceso.m


In [ ]:
!octave proceso.m

* ¿Y a largo plazo cuantos se quedan en casa?

In [83]:
%%writefile proceso.m
empleados = 1000
% state vector
inicial = [.9; .1]
% transition probability matrix
A = [.6, .3; .4, .7]
[P,D]=eig(A)
D10 = D^10
A10 = P*D10*P^-1
dia10 = A10 * inicial
disp("Nº de empleados que se quedan en casa a largo plazo son: "), disp(dia10(2)*empleados)

Overwriting proceso.m


In [84]:
!octave proceso.m

octave: X11 DISPLAY environment variable not set
octave: disabling GUI features
empleados =  1000
inicial =

   0.90000
   0.10000

A =

   0.60000   0.30000
   0.40000   0.70000

P =

  -0.70711  -0.60000
   0.70711  -0.80000

D =

Diagonal Matrix

   0.30000         0
         0   1.00000

D10 =

Diagonal Matrix

   5.9049e-06            0
            0   1.0000e+00

A10 =

   0.42857   0.42857
   0.57143   0.57143

dia10 =

   0.42857
   0.57143

Nº de empleados que se quedan en casa a largo plazo son: 
 571.43


## Práctica 3.10
**Tendencia del mercado**  
Resolver con **Python**.

En el mercado de automóviles de gran lujo únicamente se disputan la clientela dos marcas (A y B). Las ventas son $M=100.000$ automóviles anuales, no variando esta cifra con el transcurso de los años. La marca A es líder de mercado en este momento con el 75% de las ventas. Sus directivos desean consolidar su liderazgo e incluso aumentarlo, para lo cual todos los años efectúan una fuerte campaña publicitaria con la que consiguen cada año un 40% de los que fueron clientes de su competidora, aunque la empresa A pierde un 20% de sus clientes que se van a la competencia.
* ¿Cuál es la situación a los 3 años?
* ¿Y al cabo de mucho tiempo?

## Solución 3.10

* ¿Cuál es la situación a los 3 años?

In [88]:
import numpy as np

X0 = np.array([.75, .25])
A = np.array([[.8, .4], [.2 ,.6]])
X3 = A@A@A@X0
print("Situación a los tres años:", X3)

Situación a los tres años: [0.672 0.328]


* ¿Y al cabo de mucho tiempo?

In [97]:
import numpy as np

X0 = np.array([.75, .25])
A = np.array([[.8, .4], [.2 ,.6]])

d,P = np.linalg.eig(A)
D = np.diag(d)
Pinv = np.linalg.inv(P)
A10 = P@(D**10)@Pinv
X10 = A10@X0
print("Situación a los diez años:", X10)
print("Situación a los veinte años:", P@(D**20)@Pinv@X0)

Situación a los diez años: [0.6666754 0.3333246]
Situación a los veinte años: [0.66666667 0.33333333]
